---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "food-fish"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "food-fish"
  template:
    metadata:
      labels:
        app: "food-fish"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: "food-fisher"
        image: "gcr.io/aaxue-gke/food-fisher:v1"
        imagePullPolicy: "Always"
        env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: "FOOD_FISHER"
        ports:
        - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default